Use soft delete
getditto/demoapp-skyservice pull request #5
Opened 2023-03-09 21:14 UTC by texasRanger09

2023-03-09 21:35 UTC, okdistribute requested changes

2023-03-09 21:35 UTC, okdistribute commented on iOS/SkyService/Data/DataService/DataService+CartLineItems.swift
> +                    query = "workspaceId == '\(workspaceId)' && userId == '\(userId)' && orderId == '\(orderId)' deleted == false"
I think you're missing an && here

2023-03-10 02:10 UTC, kndoshn approved these changes
LGTM, thanks!

2023-03-13 21:20 UTC, magicwave commented
After downloading/installing certificates from the Apple dev portal and futzing with automatically/not-automatically manage signing with Xcode, choosing Team DittoLive Incorporated for signing on SkyService Pax and a cocoapod, Xcode build still fails because of missing Env.swift file.

2023-03-13 21:28 UTC, magicwave commented
> After downloading/installing certificates from the Apple dev portal and futzing with automatically/not-automatically manage signing with Xcode, choosing Team DittoLive Incorporated for signing on SkyService Pax and a cocoapod, Xcode build still fails because of missing Env.swift file.

Ok. I figured out that the Env.swift file needs to be built with the shell script, however build still fails because the resulting Env.swift defines only an empty struct. I suppose in order to build I'll need to create an app on the portal. Something in the README  would be helpful.

2023-03-13 23:01 UTC, okdistribute commented
Hi @magicwave, I agree this should be included in the README, as part of "Getting Started.

I just invited you to the skyservice portal app so you can see the app_id and token.

2023-03-13 23:09 UTC, okdistribute commented
@texasRanger09 Will this need the Android side as well?

2023-03-13 23:15 UTC, texasRanger09 commented
> @texasRanger09 Will this PR need to change the queries for the Android side as well?

Yes. I’m working on the android side now and will commit the changes in this PR

2023-03-13 23:50 UTC, magicwave commented
> Hi @magicwave, I agree this should be included in the README, as part of "Getting Started.
> 
> I just invited you to the skyservice portal app so you can see the app_id.

Thanks Rae, it's progress. However, the portal `skyservice-prod` app is configured with an auth provider name, but in the SkyServices code it appears that the `DittoAuthenticationDelegate` expects Env.swift to be pre-configured with a static `DITTO_AUTH_PASSWORD` value for Ditto initialization. I'm not sure where that would come from.

2023-03-14 03:36 UTC, okdistribute commented
I DMed you the password!

2023-03-14 03:56 UTC, kndoshn commented
I'll work on README ASAP. Sorry for the inconvenience.

@okdistribute 
> Makes me think that we should have a private repository with the official secrets and necessary info to publish the demo apps.

For publishing apps, I think we should just put env vars on CI/CD.

For development, I'm not very sure where we should put the env vars. We could use 1password but easy to forget updating.

2023-03-18 12:39 UTC, kndoshn approved these changes

2023-03-22 08:38 UTC, kndoshn commented
@okdistribute Can you approve and merge?

2023-03-22 14:22 UTC, okdistribute approved these changes

2023-03-22 14:22 UTC, merged